### ISSUE TITLE
password-hash library is deprecated

### ISSUE THREAD

**Issue by madblobfish** [fnordcredit/fnordcredit#240]
You may want to replace this outdated library.
The deprecation warning can be found on npm: https://www.npmjs.com/package/password-hash

Edit: its probably not the only one and you probably want to check the other deps too

**Comment by uwap** [comment]
Thanks for the issue. As the landscape of trust based cash systems changed in the past couple of years, we will be dropping pincode support for now. The dependency has been removed.
