### ISSUE TITLE
Warning: a dynamic page path "/user/[id]" was passed to "revalidatePath" without the "page" argument

### ISSUE THREAD

**Issue by uwap** [fnordcredit/fnordcredit#287]
Warning: a dynamic page path "/user/[id]" was passed to "revalidatePath" without the "page" argument. This has no affect by default, see more info here https://nextjs.org/docs/app/api-reference/functions/revalidatePath

**Comment by Ranlvor** [comment]
When adding a new user the user-list should get invalidated.
