### ISSUE TITLE
Optionale Gravatar Integration

### ISSUE THREAD

**Issue by silsha** [fnordcredit/fnordcredit#49]
Es wäre vermutlich sehr viel einfacher, wenn man dem Nutzer die Möglichkeit gibt, sein Profilkästchen zu personalisieren, z.B. indem man ihm die Möglichkeit gibt ein Avatar über Gravatar hochzuladen.

Nachteil daran ist, dass man nun auch anfangen müsste, eine E-Mail-Adresse für den Benutzer (optional) zu speichern. Was man dann allerdings auch wieder für einen monatlichen Umsatzreport oder ähnliches nutzen könnte.

Was meint ihr dazu? (@ydnax @tabascoeye)

**Comment by uwap** [comment]
Is Gravatar still a thing?

**Comment by silsha** [comment]
Yup. Plus custom avatar upload maybe?

**Comment by uwap** [comment]
![fnordcredit_gravatar_sketchup](https://user-images.githubusercontent.com/2212422/51847488-103cfe80-231c-11e9-865e-0b6477ef9375.png)

This is how I could envision the design of a user implementation. Opinions?

**Comment by tabascoeye** [comment]
Optisch schön. Aus Kassenwartsicht fänd ichs natürlich schade, nicht mehr schnell überblicken zu können, wie viele Leute im Minus sind und schnell die "Schulden" zusammenrechnen zu können...

**Comment by uwap** [comment]
@tabascoeye Was für infos brauchst du denn? Vielleicht wäre es ja sinnvoller für dich einen StatisticsView zu bauen? Oder halt einen KassenwartView?

**Comment by uwap** [comment]
Update: I just implemented the new Button class in the frontend. Below is an image of the actual new design:
![Avatar Implementation](https://user-images.githubusercontent.com/2212422/56259415-3e3c0e80-60d3-11e9-980f-c1cc9a5c9ed1.png)

Now only the backend implementation and the settings are missing for a release in 2.2 (postponed to June 2019).
